konflux-ci/caching

squid/Chart.yaml, squid/values.yaml
Updated Chart.yaml and values.yaml to include important notes indicating that the chart creates and manages its own namespace. Users are advised not to use the --namespace flag with helm commands to avoid conflicts.
=> docs(Chart.yaml, values.yaml): Add notes on namespace management

squid/Chart.lock, squid/Chart.yaml, squid/crds/cert-manager.crds.yaml, squid/values.yaml
- Add trust-manager
- Move cert-manager's CRDs to crds folder
- Update cert-manager values to not install CRDs (its taken care of by the crds folder)
The approach been used is described in https://helm.sh/docs/chart_best_practices/custom_resource_definitions/
There are some downsides for this approach (upragde or delete using helm is not supported, etc...)
We will use this approach as a mid term solution, but we should revisit it.
=> feat: add trust-manager

squid/squid.conf
Add `pid_filename none` to the squid.conf file to prevent this error:
```
2025/07/10 11:19:47| Processing Configuration File: /etc/squid/squid.conf (depth 0) 2025/07/10 11:19:47| FATAL: failed to open /run/squid.pid: (13) Permission denied
exception location: File.cc(191) open
2025/07/10 11:19:47| Processing Configuration File: /etc/squid/squid.conf (depth 0) 2025/07/10 11:19:47| FATAL: failed to open /run/squid.pid: (13) Permission denied
exception location: File.cc(191) open
```
=> fix: update squid.conf to prevent permission errors

.github/workflows/devcontainer-ci.yml
Add pull-requests: write permission to DevContainer CI workflow to enable automated posting of linter results as pull request comments. This minimal change allows future linting tools like reviewdog to post inline comments on code quality issues directly in pull requests.
=> ci(KFLUXVNGD-389): add pull-requests write permission for linter PR comments

README.md, squid/Chart.yaml, squid/crds/trust.cert-manager.io_bundles.yaml, squid/templates/cert-manager-ca-issuer.yaml, squid/templates/cert-manager-certificate.yaml, squid/templates/cert-manager-issuer.yaml, squid/templates/cert-manager-namespace.yaml, squid/templates/trust-manager-bundle.yaml, squid/values.yaml
In order to be able to create a bundle after installation we have to first make sure the bundle CRD is ready and that the trust-manager deployment is ready.
It can be achieved by creating the resources we need as template and not as post-install hook.
- Added the trust-manager's CRDs to the crds folder
- Added an option to prevent `cert-manager` and `trust-manager` from being installed (`--set installCertManagerComponents=false`) in case we are using a cluster with both already installed.
- Added an option to prevent the resources from being created by adding `--set selfsigned-bundle.enabled=false` to the helm installation command.
- Resources were added as templates instead of a post-install hook
- The config map will be spread to all namespaces
By using the added flags we can control …
=> feat(KFLUXVNGD-365): trust-manager integration for CA trust bundle

.cursor/rules/jira-todo-workflow.mdc, .devcontainer/Containerfile
Create jira-todo-workflow rule that lets you read the AC fron a Jira
issue into a TODO list for the Cursor AI agent.
Details:
- Add jq to dev container for JSON parsing (The agent keeps trying to
use it when fetching data from Jira)
- Single command workflow and small rule file to not waste space in
the token window
Signed-off-by: Barak Korren <bkorren@redhat.com>
Assisted-by: Claude-3.5-Sonnet (via Cursor)
Signed-off-by: Barak Korren <bkorren@redhat.com>
=> chore(KFLUXVNGD-388): add jira-todo workflow rule

.devcontainer/Containerfile
prevents Renovate from automatically upgrading Fedora containers to pre-release versions by using digest pinning
=> use digest pinning to prevent Fedora pre-release upgrades

.github/renovate.json
added automerge for go and go-dependencies, set autoApprove to true
=> enable safe auto-merge for more renovate dependency updates

README.md, magefile.go, squid-exporter/Containerfile, squid/values.yaml
Instead of using third party image, use our own squid-exporter image.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-402
Assisted-by: Cursor
=> chore(KFLUXVNGD-402): Use our own squid-exporter image

.tekton/squid-pull-request.yaml, .tekton/squid-push.yaml, .tekton/squid-tester-pull-request.yaml, .tekton/squid-tester-push.yaml, test.Containerfile
The Conforma policy usually used for images is excluding snyk from the requirement not to skip checks, but the current policy we're using doesn't. It does exclude it from the required tasks, so we can remove that that task altogether for now.
Also, adding labels to the tester containerfile.
=> chore: remove snyk from pipelines and add missing labels

squid/values.schema.json
Add schema for validating the values file passed to the chart
Failure example: https://github.com/konflux-ci/caching/actions/runs/16874419688/job/47795531616?pr=84
=> chore: add helm chart schema

.github/workflows/devcontainer-ci.yml, .tekton/squid-helm-pull-request.yaml, .tekton/squid-helm-push.yaml, magefile.go, squid/templates/_helpers.tpl, squid/templates/deployment.yaml, squid/templates/mirrord-target-pod.yaml, squid/templates/test-pod.yaml, squid/values.schema.json, squid/values.yaml
Adding a variable in the values file for setting the target env for
deployment. The task that builds the helm chart will then update
variables relevant for the deployment of the different environments,
and Helm helpers implemented as part of this change will select the
relevant values based on the deployment environment.
This will allow using a single values file for all environments,
constructing it during build time and releasing it as-is, rather than
having to modify it between build and release phases.
=> chore: multiple envs in helm values file

squid/squid.conf, tests/e2e/squid_deployment_test.go, tests/e2e/squid_ssl_bump_functionality_test.go
Add RAM caching to Squid.
Add e2e tests to verify RAM caching works.
Initial values for caching are:
- 256 MB RAM allocation
- Always use RAM cache
- Use `Least Frequently Used with Dynamic Aging` replacement policy
=> feat(KFLUXVNGD-360): Add RAM caching to Squid

squid/templates/proxy-certificate.yaml, tests/e2e/squid_deployment_test.go
Update proxy certificate dns names to include the fullname of the squid deployment.
=> fix: update proxy certificate dns names

.devcontainer/Containerfile
The prior version isn't able to load images into newer (v1.32.1+) kind nodes. See https://github.com/kubernetes-sigs/kind/issues/3853.
Upgrading to the latest version at the same time.
=> Update kind to v0.29.0 in the devcontainer

.github/renovate.json
removing extends line as mintmaker team advised to avoid unexpected issues
=> chore: remove renovate extends configuration

squid/squid.conf, squid/templates/deployment.yaml, squid/templates/https-test-server-bundle.yaml, squid/templates/https-test-server-selfsigned-issuer.yaml, squid/templates/https-test-server.yaml, squid/templates/test-rbac.yaml, tests/e2e/e2e_suite_test.go, tests/e2e/squid_ssl_bump_functionality_test.go, tests/testhelpers/proxy_test_helpers.go
Add internal https server for testing.
The resources are defined in the templates folder and will deployed only if `test` is enabled.
**Workflow:**
When `test` is enabled: 
* The resources needed for the https-test-server will be deployed 
* a new volume and volumeMount with the test-server bundle configmap will be added to squid's deployment (squid needs to trust the test-server)
* In order for squid to trust the https-test-server's selfsigned ca we need to add an entry to the squid.conf file and restart squid.
* The `BeforeSuite` section of the tests is responsible for it:
* We get the configmap from squid's deployment
* Check if we have the correct entry `tls_outgoing_options 
cafile=/etc/squid/trust/test-server/ca.crt`
* If it does not exist we will add it to the correct place in the …
=> feat(KFLUXVNGD-452): Use internal server for testing

.devcontainer/Containerfile, .github/workflows/devcontainer-ci.yml, .mirrord/mirrord.json, squid/squid.conf, squid/templates/configmap.yaml, squid/templates/deployment.yaml, squid/templates/test-pod.yaml, squid/templates/test-rbac.yaml, squid/values.schema.json, squid/values.yaml, test.Containerfile, tests/e2e/e2e_suite_test.go, tests/e2e/squid_cache_allow_list_test.go, tests/e2e/squid_deployment_test.go, tests/e2e/squid_metrics_test.go, tests/e2e/squid_ssl_bump_functionality_test.go, tests/testhelpers/proxy_test_helpers.go
The allow list is disabled by default, meaning all requests are cached.
Testing this feature required a number of changes to the test code/infra:
1. The squid config manager in the e2e tests is replaced with calls to helm upgrade and templating of the configmap. The squid proxy will redeploy automatically when the content of the configmap changes.
2. Disabled keep-alives in the HTTP test server to fix an issue with reuse of port 9090 between rapid tests.
3. Upgraded mirrord to 3.157.2 to fix https://github.com/metalbear-co/mirrord/issues/2653 This required setting experimental vfork_emulration=true. Encountered https://github.com/metalbear-co/mirrord/issues/3534 when trying to use 3.158+.
4. The helm binary and the squid chart needed to be added to the test container to ensure
`helm test …
=> Add support for a caching allow list using URL regex patterns

.github/renovate.json
As failures are quite common for renovate PRs for go updates, having upgrades grouped makes it harder to get those PRs merged.
Ungrouping should allow us to merge the ones that don't cause trouble and to more easily troubleshoot the ones that do.
=> chore: remove grouping of go packages in renovate

container-entrypoint.sh, squid/squid.conf, squid/templates/configmap.yaml, squid/templates/deployment.yaml, squid/values.schema.json, squid/values.yaml, tests/e2e/squid_deployment_test.go, tests/e2e/squid_ssl_bump_functionality_test.go
The max locked memory limit (ulimit -l) cannot be modified from a kubernetes pod. Squid can't lock more than ~8MB (at least, on a kind cluster) of storage in memory. To get around this, we can use disk based caching from squid's point of view but provide a tmpfs memory-backed volume for the storage.
Other included changes:
- The squid SSL DB and cache are now in separate volumes so they can be scaled independently.
- Removed unused sslDb persistent volume configuration that was never implemented.
Assisted-by: cursor(claude-4.5-sonnet)
=> Switch to disk-based cache using a memory-backed tmpfs volume

squid/templates/configmap.yaml, squid/templates/deployment.yaml, squid/values.schema.json, squid/values.yaml
The recent change to use disk caching with a memory-backed tmpfs volume makes the `memory` key unclear. Removing it since we only have a single cache medium.
=> Remove the cache.memory value
